CC = gcc
CFLAGS = -Wall -I "../../debugging" -I "../../rawIO14" -I "../../sofs14"
IFUNCS3 = soReadFileCluster.o soWriteFileCluster.o soHandleFileCluster.o soHandleFileClusters.o soCleanDataCluster.o

all:			ifuncs3

ifuncs3:		$(IFUNCS3)
