CC = gcc
CFLAGS = -Wall -I "../../debugging" -I "../../rawIO14" -I "../../sofs14"
IFUNCS4 = soGetDirEntryByPath.o soGetDirEntryByName.o soAddAttDirEntry.o soRemDetachDirEntry.o \
          soRenameDirEntry.o

all:			ifuncs4

ifuncs4:		$(IFUNCS4)
